name: "CI / CD Dulces Momentos"

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Get versions
              run: |
                  php --version
                  node --version
            
            - name: Install dependencies
              run: npm install && composer install

            - name: Create .env file
              run: |
                  cp .env.example .env
            
            - name: fill database variables
              run: |
                  echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
                  echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
                  echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
                  echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

            - name: Generate key
              run: php artisan key:generate

            - name: Run migrations
              run: php artisan migrate --env=testing
            
            - name: Run tests
              run: npm run build && php artisan test
    
    deploy:
        runs-on: ubuntu-latest
        needs: testing
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up SSH
            uses: webfactory/ssh-agent@v0.5.3
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: Verify SSH connection
            run: |
              mkdir -p ~/.ssh
              ssh-keyscan -p 65002 88.223.85.92 >> ~/.ssh/known_hosts
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '22'

          - name: Install Node.js dependencies
            run: npm install

          - name: Build assets with Vite
            run: npm run build

          - name: Deploy to Hostinger server
            run: |
              rsync -avz -e "ssh -p 65002" --exclude='.git' --exclude='node_modules' --exclude='.env' ./ u976542190@88.223.85.92:/home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com
              ssh -p 65002 u976542190@88.223.85.92 'cd /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com && composer2 install --no-dev'

          - name: Create .env file on server
            run: |
              ssh -p 65002 u976542190@88.223.85.92 'cp /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env.example /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
          
          - name: Update .env file on server
            run: |
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^APP_NAME=.*|APP_NAME=${{ secrets.APP_NAME }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^APP_ENV=.*|APP_ENV=${{ secrets.APP_ENV }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^APP_DEBUG=.*|APP_ENV=${{ secrets.APP_DEBUG }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^APP_URL=.*|APP_URL=${{ secrets.APP_URL }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^DB_CONNECTION=.*|DB_CONNECTION=${{ secrets.DB_CONNECTION }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^DB_HOST=.*|DB_HOST=${{ secrets.DB_HOST }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^DB_PORT=.*|DB_PORT=${{ secrets.DB_PORT }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^DB_DATABASE=.*|DB_DATABASE=${{ secrets.DB_DATABASE }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^DB_USERNAME=.*|DB_USERNAME=${{ secrets.DB_USERNAME }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
              ssh -p 65002 u976542190@88.223.85.92 'sed -i "s|^DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com/.env'
          - name: Deploy to Hostinger server
            run: |
              rsync -avz -e "ssh -p 65002" --exclude='.git' --exclude='node_modules' --exclude='.env' ./ u976542190@88.223.85.92:/home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com
              ssh -p 65002 u976542190@88.223.85.92 'cd /home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com && composer2 install --no-dev && php artisan migrate --force && php artisan key:generate'
          - name: Check and Copy to public_html
            run: |
              ssh -p 65002 u976542190@88.223.85.92 << 'EOF'
                # Ruta base del proyecto
                PROJECT_PATH="/home/u976542190/domains/sweetmomments-juanjozapata.jcomtec.com"
                # Verificar si la carpeta public_html existe
                if [ -d "$PROJECT_PATH/public_html" ]; then
                  echo "La carpeta public_html existe. Copiando archivos..."
                  # Copiar el contenido de la carpeta public a public_html
                  rsync -av "$PROJECT_PATH/public/" "$PROJECT_PATH/public_html/"
                else
                  echo "La carpeta public_html no existe. No se copiarán los archivos."
                fi
              EOF
